/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as InitDbRouteImport } from './routes/init-db'
import { Route as KpStudioX9z72qRouteImport } from './routes/kp-studio-x9z72q'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WorkRouteImport } from './routes/work'
import { Route as CreatorsIndexRouteImport } from './routes/creators.index'
import { Route as CreatorsDashboardRouteImport } from './routes/creators.dashboard'
import { Route as CreatorsJoinRouteImport } from './routes/creators.join'
import { Route as CreatorsLoginRouteImport } from './routes/creators.login'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const InitDbRoute = InitDbRouteImport.update({
  id: '/init-db',
  path: '/init-db',
  getParentRoute: () => rootRouteImport,
} as any)
const KpStudioX9z72qRoute = KpStudioX9z72qRouteImport.update({
  id: '/kp-studio-x9z72q',
  path: '/kp-studio-x9z72q',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsIndexRoute = CreatorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorsRoute,
} as any)
const CreatorsDashboardRoute = CreatorsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CreatorsRoute,
} as any)
const CreatorsJoinRoute = CreatorsJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => CreatorsRoute,
} as any)
const CreatorsLoginRoute = CreatorsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CreatorsRoute,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/init-db': typeof InitDbRoute
  '/kp-studio-x9z72q': typeof KpStudioX9z72qRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRouteWithChildren
  '/creators/dashboard': typeof CreatorsDashboardRoute
  '/creators/join': typeof CreatorsJoinRoute
  '/creators/login': typeof CreatorsLoginRoute
  '/work/$slug': typeof WorkSlugRoute
  '/creators/': typeof CreatorsIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/init-db': typeof InitDbRoute
  '/kp-studio-x9z72q': typeof KpStudioX9z72qRoute
  '/services': typeof ServicesRoute
  '/creators/dashboard': typeof CreatorsDashboardRoute
  '/creators/join': typeof CreatorsJoinRoute
  '/creators/login': typeof CreatorsLoginRoute
  '/work/$slug': typeof WorkSlugRoute
  '/creators': typeof CreatorsIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/init-db': typeof InitDbRoute
  '/kp-studio-x9z72q': typeof KpStudioX9z72qRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRouteWithChildren
  '/creators/dashboard': typeof CreatorsDashboardRoute
  '/creators/join': typeof CreatorsJoinRoute
  '/creators/login': typeof CreatorsLoginRoute
  '/work/$slug': typeof WorkSlugRoute
  '/creators/': typeof CreatorsIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/creators'
    | '/init-db'
    | '/kp-studio-x9z72q'
    | '/services'
    | '/work'
    | '/creators/dashboard'
    | '/creators/join'
    | '/creators/login'
    | '/work/$slug'
    | '/creators/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/init-db'
    | '/kp-studio-x9z72q'
    | '/services'
    | '/creators/dashboard'
    | '/creators/join'
    | '/creators/login'
    | '/work/$slug'
    | '/creators'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/creators'
    | '/init-db'
    | '/kp-studio-x9z72q'
    | '/services'
    | '/work'
    | '/creators/dashboard'
    | '/creators/join'
    | '/creators/login'
    | '/work/$slug'
    | '/creators/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CreatorsRoute: typeof CreatorsRouteWithChildren
  InitDbRoute: typeof InitDbRoute
  KpStudioX9z72qRoute: typeof KpStudioX9z72qRoute
  ServicesRoute: typeof ServicesRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init-db': {
      id: '/init-db'
      path: '/init-db'
      fullPath: '/init-db'
      preLoaderRoute: typeof InitDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kp-studio-x9z72q': {
      id: '/kp-studio-x9z72q'
      path: '/kp-studio-x9z72q'
      fullPath: '/kp-studio-x9z72q'
      preLoaderRoute: typeof KpStudioX9z72qRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/': {
      id: '/creators/'
      path: '/'
      fullPath: '/creators/'
      preLoaderRoute: typeof CreatorsIndexRouteImport
      parentRoute: typeof CreatorsRoute
    }
    '/creators/dashboard': {
      id: '/creators/dashboard'
      path: '/dashboard'
      fullPath: '/creators/dashboard'
      preLoaderRoute: typeof CreatorsDashboardRouteImport
      parentRoute: typeof CreatorsRoute
    }
    '/creators/join': {
      id: '/creators/join'
      path: '/join'
      fullPath: '/creators/join'
      preLoaderRoute: typeof CreatorsJoinRouteImport
      parentRoute: typeof CreatorsRoute
    }
    '/creators/login': {
      id: '/creators/login'
      path: '/login'
      fullPath: '/creators/login'
      preLoaderRoute: typeof CreatorsLoginRouteImport
      parentRoute: typeof CreatorsRoute
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface CreatorsRouteChildren {
  CreatorsDashboardRoute: typeof CreatorsDashboardRoute
  CreatorsJoinRoute: typeof CreatorsJoinRoute
  CreatorsLoginRoute: typeof CreatorsLoginRoute
  CreatorsIndexRoute: typeof CreatorsIndexRoute
}

const CreatorsRouteChildren: CreatorsRouteChildren = {
  CreatorsDashboardRoute: CreatorsDashboardRoute,
  CreatorsJoinRoute: CreatorsJoinRoute,
  CreatorsLoginRoute: CreatorsLoginRoute,
  CreatorsIndexRoute: CreatorsIndexRoute,
}

const CreatorsRouteWithChildren = CreatorsRoute._addFileChildren(
  CreatorsRouteChildren,
)

interface WorkRouteChildren {
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CreatorsRoute: CreatorsRouteWithChildren,
  InitDbRoute: InitDbRoute,
  KpStudioX9z72qRoute: KpStudioX9z72qRoute,
  ServicesRoute: ServicesRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
